# Generated by Django 5.0.7 on 2024-07-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
