# Generated by Django 5.0.7 on 2024-08-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='imagepath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
