# Generated by Django 5.0.7 on 2024-08-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_imagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
